// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import router "test/amartha/router"

// RouterIO is an autogenerated mock type for the RouterIO type
type RouterIO struct {
	mock.Mock
}

// GET provides a mock function with given fields: path, handle
func (_m *RouterIO) GET(path string, handle router.Handle) {
	_m.Called(path, handle)
}

// POST provides a mock function with given fields: path, handle
func (_m *RouterIO) POST(path string, handle router.Handle) {
	_m.Called(path, handle)
}

// Serve provides a mock function with given fields: port
func (_m *RouterIO) Serve(port string) {
	_m.Called(port)
}
